version: '3'

services:
  # App Service
  my_app:    
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: backend_app
    hostname: backend
    restart: unless-stopped
    tty: true
    networks: 
      - app-network

 #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_app_db
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
